---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spot-interrupt-handler
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spot-interrupt-handler
  namespace: kube-system
  labels:
    app: spot-interrupt-handler
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spot-interrupt-handler
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: spot-interrupt-handler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: spot-interrupt-handler
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-interrupt-handler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: spot-interrupt-handler
  template:
    metadata:
      labels:
        app: spot-interrupt-handler
    spec:
      serviceAccountName: spot-interrupt-handler
      containers:
      - name: spot-interrupt-handler
        image: kubeaws/kube-spot-termination-notice-handler:1.11.3-1
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPOT_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SLACK_URL
          value: "https://hooks.slack.com/services/SOME/TOKEN"
        - name: CLUSTER
          value: "development"
      nodeSelector:
#        lifecycle: Ec2Spot
        type: spot
      tolerations:
        - operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
